1c1,3
< FROM        quay.io/prometheus/busybox:glibc
---
> FROM armhf/alpine:latest
> ADD qemu-arm-static /usr/bin
> RUN apk update && apk add libc6-compat && ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3
