1,2c1,2
< FROM        quay.io/prometheus/busybox:latest
< LABEL maintainer "The Prometheus Authors <prometheus-developers@googlegroups.com>"
---
> FROM armhf/alpine:latest
> ADD qemu-arm-static /usr/bin
