1c1,3
< FROM        quay.io/prometheus/busybox:latest
---
> FROM arm64v8/alpine:latest
> ADD qemu-aarch64-static /usr/bin
> RUN apk update && apk add libc6-compat && ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3
