1,2c1,3
< FROM        quay.io/prometheus/busybox:glibc
< MAINTAINER  The Prometheus Authors <prometheus-developers@googlegroups.com>
---
> FROM armhf/alpine:latest
> ADD qemu-arm-static /usr/bin
> RUN apk update && apk add libc6-compat
