1c1
< FROM alpine:3.4
---
> FROM armhf/lpine:3.4
6c6
< ENV PROMETHEUS_VERSION 1.2.1
---
> ENV PROMETHEUS_VERSION 1.6.2
16c16
<   wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"; \
---
>   wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-armv7.tar.gz"; \
