1c1,2
< FROM alpine:3.4
---
> FROM armhf/alpine:3.4
> ADD qemu-arm-static /usr/bin
6c7
< ENV PROMETHEUS_VERSION 1.2.1
---
> ENV PROMETHEUS_VERSION 1.6.2
16c17
< 	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-amd64.tar.gz"; \
---
> 	wget -O /tmp/prom.tar.gz "https://github.com/prometheus/prometheus/releases/download/v${PROMETHEUS_VERSION}/prometheus-${PROMETHEUS_VERSION}.linux-armv7.tar.gz"; \
