--- Dockerfile.x86
+++ Dockerfile.arm
@@ -1,4 +1,5 @@
-FROM        quay.io/prometheus/busybox:latest
+FROM arm64v8/alpine:latest
+ADD qemu-aarch64-static /usr/bin
 LABEL maintainer "The Prometheus Authors <prometheus-developers@googlegroups.com>"

 COPY prometheus                             /bin/prometheus
